# Site settings
title: "Desri + Ross"
description: |
    Cheam, Surrey

    20 January 2020
owner: Ross Ewart
first_published: 2019
email: forsey+wedding@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://d2gfjgbfqrlvzv.cloudfront.net" # the base hostname & protocol for your site

social:
  github: https://github.com/theon/ross-desri-wedding-site

# Build settings
markdown: kramdown
